#!/usr/bin/env python3
"""Import shared translations as native Android resources (no build-time iOS dependency)."""
import hashlib
import json
import re
import sys
from pathlib import Path
from xml.sax.saxutils import escape

ROOT = Path(__file__).resolve().parents[2]
LANGUAGES = ['de', 'es', 'fr', 'it', 'ja', 'ko', 'nl', 'pl', 'pt-BR', 'ro', 'ru', 'tr', 'uk', 'zh-Hans', 'zh-Hant']
QUALIFIERS = {'pt-BR': 'pt-rBR', 'zh-Hans': 'b+zh+Hans', 'zh-Hant': 'b+zh+Hant'}

def resource_name(source):
    slug = re.sub('[^a-z0-9]+', '_', source.lower()).strip('_')[:55]
    return 'l10n_' + slug + '_' + hashlib.sha256(source.encode()).hexdigest()[:8]

def xml_text(value):
    return '"' + escape(value.replace('\\', '\\\\').replace('"', '\\"').replace("'", "\\'").replace('\n', '\\n')) + '"'

def format_string(value):
    # Positional string parameters preserve the translated word order. Numeric
    # arguments are formatted by callers, so no language-specific type is lost.
    i = 0
    def replace(m):
        nonlocal i
        if m.group() == '%%': return '%%'
        i += 1
        return '%' + (m.group(1) or str(i)) + '$s'
    return re.sub(r'%(?:(\d+)\$)?(?:@|lld|llu|ld|lu|d|u|\.\d+f|f)|%%', replace, value)

def main():
    catalog = json.loads(Path(sys.argv[1]).read_text())['strings']
    aliases = json.loads((ROOT / 'scripts/localization/aliases.json').read_text())
    extra = json.loads((ROOT / 'scripts/localization/android.json').read_text())
    entries = {}
    plurals = {}
    for source, item in catalog.items():
        locs = item.get('localizations', {})
        if not all('plural' in locs.get(lang, {}).get('variations', {}) for lang in ['en'] + LANGUAGES):
            continue
        key = re.sub(r'%\d+\$s', '%s', format_string(source))
        plurals[key] = {lang: {q: format_string(v['stringUnit']['value'])
                              for q, v in locs[lang]['variations']['plural'].items()}
                        for lang in ['en'] + LANGUAGES}
    for source, item in catalog.items():
        locs = item.get('localizations', {})
        # Plurals are imported separately once callers provide explicit counts.
        if source and all('stringUnit' in locs.get(lang, {}) for lang in LANGUAGES):
            entries[re.sub(r'%\d+\$s', '%s', format_string(source))] = {lang: format_string(locs[lang]['stringUnit']['value']) for lang in LANGUAGES}
    for source, target in aliases.items():
        if re.sub(r'%\d+\$s', '%s', format_string(target)) not in entries: raise ValueError('Missing iOS translation: ' + target)
        entries[source] = entries[re.sub(r'%\d+\$s', '%s', format_string(target))]
    for source, translations in extra.items():
        if set(translations) != set(LANGUAGES): raise ValueError('Incomplete translation: ' + source)
        entries[source] = translations
    for lang in ['en'] + LANGUAGES:
        folder = ROOT / 'app/src/main/res' / ('values' if lang == 'en' else 'values-' + QUALIFIERS.get(lang, lang))
        folder.mkdir(parents=True, exist_ok=True)
        lines = ['<?xml version="1.0" encoding="utf-8"?>', '<!-- Generated by scripts/localization/import_ios.py -->', '<resources>']
        for source, translations in sorted(entries.items()):
            # tr does formatting itself; Android must retain literal %s/%%.
            lines.append(f'    <string name="{resource_name(source)}" formatted="false">{xml_text(source if lang == "en" else translations[lang])}</string>')
        for source, translations in sorted(plurals.items()):
            lines.append(f'    <plurals name="{resource_name(source)}">')
            for quantity, value in translations[lang].items():
                lines.append(f'        <item quantity="{quantity}">{xml_text(value)}</item>')
            lines.append('    </plurals>')
        lines.append('</resources>')
        (folder / 'strings_localized.xml').write_text('\n'.join(lines) + '\n')
    dest = ROOT / 'app/src/main/java/one/monero/moneroone/core/locale/LocalizedStrings.kt'
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text('''package one.monero.moneroone.core.locale

import one.monero.moneroone.R

// Generated by scripts/localization/import_ios.py.
internal val localizedStrings: Map<String, Int> = mapOf(
''' + '\n'.join('    ' + json.dumps(source, ensure_ascii=False).replace('$', '\\$') + ' to R.string.' + resource_name(source) + ',' for source in sorted(entries)) + '\n)\n')
    with dest.open('a') as f:
        f.write('\ninternal val localizedPlurals: Map<String, Int> = mapOf(\n' +
                '\n'.join('    ' + json.dumps(source, ensure_ascii=False).replace('$', '\\$') + ' to R.plurals.' + resource_name(source) + ',' for source in sorted(plurals)) + '\n)\n')
    print(f'Imported {len(entries)} messages in English and {len(LANGUAGES)} translations')

if __name__ == '__main__': main()
